# WARNING: This stack depends on traefik.yml stack
# STACK_BASE_PATH [base folder where to host files, must exists]
# DOMAIN: base domain for LE certificates

version: '3.7'

services:
  echoip:
    image: neomediatech/echoip
    hostname: echoip
    networks:
      - traefik-public
    command: ["--trusted-header=X-Real-IP", "-r"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.port=8080"
        - "traefik.tags=traefik-public"
        - "traefik.redirectorservice.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:ip.${DOMAIN}"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rateLimit.rateSet.test.period=10s"
        - "traefik.frontend.rateLimit.rateSet.test.burst=5"
        - "traefik.frontend.rateLimit.rateSet.test.average=4"
        - "traefik.frontend.rateLimit.extractorFunc=client.ip"
    volumes:
      - ${STACK_BASE_PATH}/index.html:/opt/echoip/index.html:ro

networks:
  traefik-public:
    external: true

